Fix possible crash in Gallery.
This fixes a long-standing TODO in the metadata of gallery items,
that no longer retrieves metadata by reflection, and forces consumers
to use the explicit fields provided by ExtMetadata.

I've actually observed a crash that was caused by the old behavior,
and this patch resolves it.

java.lang.ClassCastException: java.lang.Long cannot be cast to org.wikipedia.gallery.ExtMetadata$Values
at org.wikipedia.gallery.ExtMetadata.toMap(ExtMetadata.java:64)
at org.wikipedia.gallery.GalleryItem.<init>(GalleryItem.java:37)

Change-Id: I8e1a44d8ec76edc9be43addf43237dc69633f155