Fix: prevent possible internal exception when fetching user options.
Lately, in logcat, I've been noticing some exceptions of the following
form:

java.lang.NumberFormatException: For input string: "0.0"
at java.lang.Integer.parseInt(Integer.java:521)
at java.lang.Integer.valueOf(Integer.java:611)
at org.wikipedia.useroption.database.UserOptionDao$2.onFinish(UserOptionDao.java:60)

(This is when we're fetching the fontSize preference)
So then, this is implying that even though we upload the preference as an
integer, the server can send it back as a float (?)
Therefore we need to account for this condition when parsing the option
string.

Change-Id: Ifdfff62ccd566b619f12e925795b5b5ea650fd4e