Update robolectric to 3.3.2
Features:
* Initial support for Android O runtime [issue #2988].

Bug Fixes:
* Fix issues with PackageManager simulation: addPackage() should not create
  sessions [issues #2984 and #2950].
* Fix deadlock caused by synchronicity of Scheduler [issues #2115, #1043,
  and #2982].
* Fix NoClassDefFoundError: javax/microedition/khronos/opengles/GL [issues
  #2960 and #1932].
* Fixed: instrumentation fails for abstract subclasses of framework classes
  [issue #2951 and #2983].

Misc:
* Switch from VTD to StAX for parsing resource xml; resolves licensing
  issue and reduces resource parsing time by about 60% [issues #2964,
  #2865, and #1414].
* Clean up temp dirs left behind after test runs.

https://github.com/robolectric/robolectric/releases

Change-Id: I0f49c3bb96ab3bec2114c9f7bab22707aea06be8