Reset Android emulator clock before running tests
The Android emulator clock is often significantly out of sync. This
causes network failures like:

  java.lang.RuntimeException: org.mediawiki.api.json.ApiException: javax.net.ssl.SSLHandshakeException: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: current time: Fri Sep 04 09:18:17 GMT+00:00 2015, validation time: Thu Dec 10 23:22:05 GMT+00:00 2015

This patch resets the clock to the current time.

[0] https://integration.wikimedia.org/ci/job/apps-android-wikipedia-periodic-test/263/console

Change-Id: I37a6a0b48aa7df902975b9522d63a1fb54e8234a